config/routes.rb
Rails.application.routes.draw do
  get 'game/game_index'
  get 'profilepage/profile'

  devise_for :users
  get 'landing_page/index'
  root 'landing_page#index'
  get 'profilepage' => 'profilepage#profile'
  get 'profilepage/edit'
  post 'profilepage/edit' => 'profilepage#attachprofilepicture'
  get 'profilepage/attachprofilepicture' => 'profilepage'

  post 'pets/create' => 'pets#create'
  post 'profilepage/addpicture'

  get 'contact' => 'landing_page#contact'
  post 'request_contact' => 'landing_page#request_contact'

  get 'game' => 'game#game_index'
  post 'game' => 'game#game_index'
  get 'game/pick_left'
  get 'game/pick_right'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_footer.html.erb
<div id="footercontainer">
  <%= image_tag 'FooterDesign.png' %>
  <div id="outerdiv">
    <div id="innerdiv">
      <div id="contactflexbox">
        <%= link_to(t('footer.contactme'),contact_path, method: "GET") %>
        <%# This link is only for debugging and marking, and wouldn't be in a production build%>
        <%= link_to(t('footer.mailer'),"/rails/mailers") %>
      </div>
      <p>|</p>
      <%= link_to(t('footer.github'),"https://github.com/Khazoda/Adorapet") %>
      <p>|</p>
      <%= content_tag :p, t('footer.copyright') %>
    </div>
  </div>
</div>

app/views/pages/_header.html.erb
<div id="left">
  <%= image_tag 'lightdark.png',id:"darktheme" %>
</div>
<div id="center">
  <%= content_tag :h1, header,id:"h1" %>
  <% if user_signed_in? %>
    <%# If current page is the landing page..%>
    <% if current_page?("/")%>
      <%# add play button to header%>
      <%= button_to t('header.play'), game_path, id:"play",method: :get %>
      <%# else add a button to return to landing page%>
    <% else %>
      <%= button_to t('header.home'), root_path, id:"gohome", method: :get %>
    <% end %>
  <% end %>
</div>
<div id="right">
  <%# displays different top right elements based on user login status%>
  <% if user_signed_in? %>
    <%= content_tag :div,content_tag(:p,current_user.likes,class:"likes")+content_tag(:p,t('header.likes'),class:"likes"),id:"likesrankcontainer"%>
    <% if current_user.avatar.attached? %>
      <%= link_to image_tag(current_user.avatar, :alt => "usericon", class:"usericon active"),profilepage_profile_path %>
    <% else %>
      <%= link_to image_tag("default_user.svg", :alt => "usericon", class:"usericon active"),profilepage_profile_path %>
    <% end %>
  <% else %>
    <%= image_tag("default_user.svg", :alt => "usericon", class:"usericon") %>
  <% end %>
  <% if user_signed_in? %>
    <div>
      <%= content_tag :p, current_user.username,id:"username" %><br/>
      <%= button_to t('header.logout'), destroy_user_session_path, id:"logout", method: :delete %>
    </div>
  <% else %>
    <div id="loginsignupcontainer">
      <%= button_to 'Log In', new_user_session_path, id:"login", method: :get %>
      <%= button_to 'Register', new_user_registration_path, id:"register", method: :get %>
      <div>
      <% end %>
    </div>